/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_HnswMemTableConfig */

#ifndef _Included_org_rocksdb_HnswMemTableConfig
#define _Included_org_rocksdb_HnswMemTableConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_HnswMemTableConfig
 * Method:    newMemTableFactoryHandle0
 * Signature: (JBJJJJJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_HnswMemTableConfig_newMemTableFactoryHandle0
  (JNIEnv *, jobject, jlong, jbyte, jlong, jlong, jlong, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
