/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_VectorSearchOptions */

#ifndef _Included_org_rocksdb_VectorSearchOptions
#define _Included_org_rocksdb_VectorSearchOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    newVectorSearchOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_newVectorSearchOptions__
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    newVectorSearchOptions
 * Signature: (ZZ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_newVectorSearchOptions__ZZ
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    copyVectorSearchOptions
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_copyVectorSearchOptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    k
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_k
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setK
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setK
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    ts
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_ts
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTs
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    evict
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_evict
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setEvict
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setEvict
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    triggerSort
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_triggerSort
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTriggerSort
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTriggerSort
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    terminationFactor
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_rocksdb_VectorSearchOptions_terminationFactor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTerminationFactor
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTerminationFactor
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    searchSST
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_searchSST
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setSearchSST
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setSearchSST
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_disposeInternal
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    verifyChecksums
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_verifyChecksums
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setVerifyChecksums
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setVerifyChecksums
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    fillCache
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_fillCache
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setFillCache
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setFillCache
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    snapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_snapshot
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setSnapshot
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    readTier
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_org_rocksdb_VectorSearchOptions_readTier
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setReadTier
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setReadTier
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    tailing
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_tailing
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTailing
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTailing
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    managed
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_managed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setManaged
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setManaged
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    totalOrderSeek
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_totalOrderSeek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTotalOrderSeek
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTotalOrderSeek
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    prefixSameAsStart
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_prefixSameAsStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setPrefixSameAsStart
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setPrefixSameAsStart
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    pinData
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_pinData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setPinData
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setPinData
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    backgroundPurgeOnIteratorCleanup
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_backgroundPurgeOnIteratorCleanup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setBackgroundPurgeOnIteratorCleanup
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setBackgroundPurgeOnIteratorCleanup
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    readaheadSize
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_readaheadSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setReadaheadSize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setReadaheadSize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    maxSkippableInternalKeys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_maxSkippableInternalKeys
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setMaxSkippableInternalKeys
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setMaxSkippableInternalKeys
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    ignoreRangeDeletions
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_ignoreRangeDeletions
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setIgnoreRangeDeletions
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setIgnoreRangeDeletions
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setIterateUpperBound
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setIterateUpperBound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    iterateUpperBound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_iterateUpperBound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setIterateLowerBound
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setIterateLowerBound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    iterateLowerBound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_iterateLowerBound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTableFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTableFilter
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    autoPrefixMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_autoPrefixMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setAutoPrefixMode
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setAutoPrefixMode
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    timestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_timestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setTimestamp
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setTimestamp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    iterStartTs
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_iterStartTs
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setIterStartTs
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setIterStartTs
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    deadline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_deadline
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setDeadline
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setDeadline
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    ioTimeout
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_ioTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setIoTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setIoTimeout
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    valueSizeSoftLimit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_VectorSearchOptions_valueSizeSoftLimit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setValueSizeSoftLimit
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setValueSizeSoftLimit
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    asyncIO
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_VectorSearchOptions_asyncIO
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_rocksdb_VectorSearchOptions
 * Method:    setAsyncIO
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_VectorSearchOptions_setAsyncIO
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
