/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_HnswTableOptions */

#ifndef _Included_org_rocksdb_HnswTableOptions
#define _Included_org_rocksdb_HnswTableOptions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_HnswTableOptions
 * Method:    newTableFactoryHandle
 * Signature: (ZZZZBBDBZJJJIIIJZZZJZZIIZZBJIJBJ)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_HnswTableOptions_newTableFactoryHandle
  (JNIEnv *, jobject, jboolean, jboolean, jboolean, jboolean, jbyte, jbyte, jdouble, jbyte, jboolean, jlong, jlong, jlong, jint, jint, jint, jlong, jboolean, jboolean, jboolean, jlong, jboolean, jboolean, jint, jint, jboolean, jboolean, jbyte, jlong, jint, jlong, jbyte, jlong);

#ifdef __cplusplus
}
#endif
#endif
