hdfsAddress: "hdfs://10.214.151.20:9000"
hdfsUser: "auroflow"
sourcePath: "/user/auroflow/vector_search/dataset/vectors/bigann_base.txt"
queryPath: "/user/auroflow/vector_search/dataset/vectors/bigann_query.txt"
vectorDim: 128
# To control the insert rate in a staged manner, set the thresholds for the number of vectors inserted, where the rate changes
insertThrottleThresholds: [0, 80000000]
# The insert rates at each stage
insertRates: [15000, 8000]
# The rate observed by the system
fakeInsertRate: 8000
# To control the query rate in a staged manner, set the thresholds for the number of queries, where the rate changes
queryThrottleThresholds: [0, 533]
# The query rates at each stage
queryRates: [-10, -2]
# Loop the queries
queryExecuteLoop: 1
k: 10
parallelism: 160 # 12 #
reduceParallelism: 1 # 1 #
numCopies: 1
maxTTL: 2400000
partitioner: "lsh+hilbert"  # supports ["lsh+hilbert", "simple"]
proximity: 1
metricType: "L2"
lshNumFamilies: 8  # number of hash families, This controls the fanout for each vector and query.
lshNumHashes: 10  # number of hash functions in each family
lshBucketWidth: 5  # hash bucket width
lshNumHilbertBits: 7  # number of bits used for hilbert curve
lshPartitionUpdateInterval: 7200000  # interval for partition update in millis
lshHilbertMaxRetainedElements: 1000000 # number of vectors retained to obtain the next partition scheme
hnswM: 16
hnswEfSearch: 16
hnswEfConstruction: 128
rocksDBMaxElementsPerHnswTable: 250000 # 250000 #
rocksDBSSTableSize: 8589934592  # Default: 8196 MB
rocksDBBlockSize: 131072  # Default: 128 KB
rocksDBBlockCacheSize: 26214400  # 25 MB
rocksDBMaxBackgroundJobs: 11  # flushes & compaction
rocksDBFlushThreshold: 2
rocksDBMaxWriteBufferNumber: 5
rocksDBTerminationWeight: 0.01
rocksDBTerminationFactor: 0.8
rocksDBTerminationThreshold: 0
rocksDBTerminationLowerBound: 0
rocksDBBlockRestartInterval: 4
milvusCollectionName: "vector_collection"
milvusHost: "10.214.242.182"
milvusPort: 19530
milvusNumShards: 4
milvusInsertBufferCapacity: 1000
milvusQueryBufferCapacity: 10
groundTruthPath: "/home/auroflow/code/vector-search/data/sift/sift_groundtruth.ivecs"
fileSinkPath: "hdfs://10.214.151.20:9000/user/auroflow/vector_search/rocksdb-logs"
sortInterval: 100
